version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cuca_backend
    restart: always
    ports:
      - "${PORT}:${PORT}"   # usa a porta dinâmica que o Railway fornece
    env_file:
      - ./backend/.env
    environment:
      - PORT=${PORT}
